version: '3.9'
services:
  api:
    build: .
    container_name: pichallenge1
    ports:
      - '8000:8000'
    volumes:
      - ./app :/app
    command: [ "fastapi", "run", "main.py", "--port", "8000" ]
    expose:
      - 8000

  db:
    image: keinos/sqlite3:3.46.0
    container_name: sqlite3
    stdin_open: true
    tty: true
    volumes:
      - sqlite_data:/var/lib/sqlite/data
    expose:
      - 8080

volumes:
  sqlite_data:
